alias ls='eza --icons --group-directories-first'
alias la='ls -la'
alias lla='ls -la'
alias ld='ls -D'
alias lt='ls --tree'
alias lgs='ls --git'
alias ltgs='ls --git --tree=3'
alias lsgs='ls --git -l'
alias cat='bat'
